export type ExportFormat = "csv" | "pdf" | "docx";

export interface ExportColumn<Row> {
	header: string;
	value: (row: Row) => string | number;
}

export interface ReportExportPayload {
	title: string;
	generatedAt: string;
	generatedBy: string;
	filters: Record<string, string>;
	kpis: Array<{ label: string; value: string | number }>;
	summary: string;
	chartSeries: Array<{ title: string; rows: Array<{ label: string; value: string | number }> }>;
	sectionSummaries: Array<{ title: string; totalRows: number }>;
}

function triggerDownload(blob: Blob, filename: string) {
	const url = URL.createObjectURL(blob);
	const anchor = document.createElement("a");
	anchor.href = url;
	anchor.download = filename;
	document.body.appendChild(anchor);
	anchor.click();
	document.body.removeChild(anchor);
	URL.revokeObjectURL(url);
}

function asText(value: string | number | null | undefined): string {
	if (value === null || value === undefined) return "";
	return String(value);
}

export async function exportRows<Row>(options: { format: ExportFormat; title: string; filenameBase: string; columns: ExportColumn<Row>[]; rows: Row[]; metadata?: Record<string, string | number> }) {
	const { format, title, filenameBase, columns, rows, metadata = {} } = options;

	if (format === "csv") {
		const lines: string[] = [];

		lines.push(["Report", title].join(","));
		Object.entries(metadata).forEach(([key, value]) => {
			lines.push([key, asText(value)].map((v) => `"${v.replace(/"/g, '""')}"`).join(","));
		});
		lines.push("");

		lines.push(columns.map((col) => `"${col.header.replace(/"/g, '""')}"`).join(","));
		rows.forEach((row) => {
			lines.push(columns.map((col) => `"${asText(col.value(row)).replace(/"/g, '""')}"`).join(","));
		});

		triggerDownload(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" }), `${filenameBase}.csv`);
		return;
	}

	if (format === "pdf") {
		const { jsPDF } = await import("jspdf");
		const autoTable = (await import("jspdf-autotable")).default;

		const doc = new jsPDF({ orientation: "landscape" });
		doc.setFontSize(16);
		doc.text(title, 14, 16);

		doc.setFontSize(10);
		let currentY = 24;
		Object.entries(metadata).forEach(([key, value]) => {
			doc.text(`${key}: ${asText(value)}`, 14, currentY);
			currentY += 5;
		});

		autoTable(doc, {
			startY: currentY + 2,
			head: [columns.map((column) => column.header)],
			body: rows.map((row) => columns.map((column) => asText(column.value(row)))),
			theme: "striped",
			headStyles: { fillColor: [91, 33, 54] },
			styles: { fontSize: 8 },
		});

		doc.save(`${filenameBase}.pdf`);
		return;
	}

	const docx = await import("docx");
	const { Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableCell, TableRow, WidthType } = docx;

	const metadataParagraphs = Object.entries(metadata).map(
		([key, value]) =>
			new Paragraph({
				children: [new TextRun({ text: `${key}: `, bold: true }), new TextRun({ text: asText(value) })],
			}),
	);

	const table = new Table({
		width: { size: 100, type: WidthType.PERCENTAGE },
		rows: [
			new TableRow({
				children: columns.map(
					(column) =>
						new TableCell({
							children: [new Paragraph({ text: column.header })],
						}),
				),
			}),
			...rows.map(
				(row) =>
					new TableRow({
						children: columns.map(
							(column) =>
								new TableCell({
									children: [new Paragraph({ text: asText(column.value(row)) })],
								}),
						),
					}),
			),
		],
	});

	const document = new Document({
		sections: [
			{
				children: [new Paragraph({ text: title, heading: HeadingLevel.HEADING_1 }), ...metadataParagraphs, new Paragraph({ text: "" }), table],
			},
		],
	});

	const blob = await Packer.toBlob(document);
	triggerDownload(blob, `${filenameBase}.docx`);
}

export async function exportFullReport(format: ExportFormat, payload: ReportExportPayload) {
	const metadata: Record<string, string> = {
		"Generated At": payload.generatedAt,
		"Generated By": payload.generatedBy,
		...payload.filters,
	};

	if (format === "csv") {
		const lines: string[] = [];
		lines.push(`"${payload.title}"`);
		lines.push("");
		lines.push("Metadata");
		Object.entries(metadata).forEach(([key, value]) => {
			lines.push(`"${key}","${value.replace(/"/g, '""')}"`);
		});

		lines.push("");
		lines.push("KPI Summary");
		lines.push("Metric,Value");
		payload.kpis.forEach((kpi) => {
			lines.push(`"${kpi.label.replace(/"/g, '""')}","${asText(kpi.value).replace(/"/g, '""')}"`);
		});

		lines.push("");
		lines.push("Executive Summary");
		lines.push(`"${payload.summary.replace(/"/g, '""')}"`);

		payload.chartSeries.forEach((series) => {
			lines.push("");
			lines.push(`"${series.title.replace(/"/g, '""')}"`);
			lines.push("Label,Value");
			series.rows.forEach((row) => {
				lines.push(`"${row.label.replace(/"/g, '""')}","${asText(row.value).replace(/"/g, '""')}"`);
			});
		});

		lines.push("");
		lines.push("Section Totals");
		lines.push("Section,Rows");
		payload.sectionSummaries.forEach((section) => {
			lines.push(`"${section.title.replace(/"/g, '""')}","${section.totalRows}"`);
		});

		triggerDownload(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" }), "abtf-admin-report.csv");
		return;
	}

	if (format === "pdf") {
		const { jsPDF } = await import("jspdf");
		const autoTable = (await import("jspdf-autotable")).default;

		const doc = new jsPDF({ orientation: "portrait" });
		doc.setFontSize(16);
		doc.text(payload.title, 14, 18);

		doc.setFontSize(10);
		let y = 26;
		Object.entries(metadata).forEach(([key, value]) => {
			doc.text(`${key}: ${value}`, 14, y);
			y += 5;
		});

		autoTable(doc, {
			startY: y + 2,
			head: [["KPI", "Value"]],
			body: payload.kpis.map((kpi) => [kpi.label, asText(kpi.value)]),
			theme: "striped",
			headStyles: { fillColor: [91, 33, 54] },
			styles: { fontSize: 9 },
		});

		y = ((doc as typeof doc & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || y) + 10;
		doc.setFontSize(12);
		doc.text("Executive Summary", 14, y);
		y += 6;

		doc.setFontSize(9);
		const summaryLines = doc.splitTextToSize(payload.summary, 180);
		doc.text(summaryLines, 14, y);
		y += summaryLines.length * 4 + 6;

		payload.chartSeries.forEach((series) => {
			autoTable(doc, {
				startY: y,
				head: [[series.title, "Value"]],
				body: series.rows.map((row) => [row.label, asText(row.value)]),
				theme: "grid",
				headStyles: { fillColor: [31, 41, 55] },
				styles: { fontSize: 8 },
			});
			y = ((doc as typeof doc & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || y) + 6;
			if (y > 260) {
				doc.addPage();
				y = 20;
			}
		});

		autoTable(doc, {
			startY: y,
			head: [["Detailed Section", "Rows Included"]],
			body: payload.sectionSummaries.map((section) => [section.title, String(section.totalRows)]),
			theme: "striped",
			headStyles: { fillColor: [55, 65, 81] },
			styles: { fontSize: 8 },
		});

		doc.save("abtf-admin-report.pdf");
		return;
	}

	const docx = await import("docx");
	const { Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableCell, TableRow, WidthType } = docx;

	const reportTable = (title: string, rows: Array<[string, string]>) =>
		new Table({
			width: { size: 100, type: WidthType.PERCENTAGE },
			rows: [
				new TableRow({
					children: [new TableCell({ children: [new Paragraph({ text: title, heading: HeadingLevel.HEADING_3 })] }), new TableCell({ children: [new Paragraph({ text: "Value", heading: HeadingLevel.HEADING_3 })] })],
				}),
				...rows.map(
					([label, value]) =>
						new TableRow({
							children: [new TableCell({ children: [new Paragraph({ text: label })] }), new TableCell({ children: [new Paragraph({ text: value })] })],
						}),
				),
			],
		});

	const children = [
		new Paragraph({ text: payload.title, heading: HeadingLevel.HEADING_1 }),
		...Object.entries(metadata).map(
			([key, value]) =>
				new Paragraph({
					children: [new TextRun({ text: `${key}: `, bold: true }), new TextRun({ text: value })],
				}),
		),
		new Paragraph({ text: "" }),
		new Paragraph({ text: "Executive Summary", heading: HeadingLevel.HEADING_2 }),
		new Paragraph({ text: payload.summary }),
		new Paragraph({ text: "" }),
		reportTable(
			"KPI Summary",
			payload.kpis.map((kpi) => [kpi.label, asText(kpi.value)]),
		),
		new Paragraph({ text: "" }),
	];

	payload.chartSeries.forEach((series) => {
		children.push(
			reportTable(
				series.title,
				series.rows.map((row) => [row.label, asText(row.value)]),
			),
		);
		children.push(new Paragraph({ text: "" }));
	});

	children.push(
		reportTable(
			"Section Totals",
			payload.sectionSummaries.map((section) => [section.title, String(section.totalRows)]),
		),
	);

	const document = new Document({
		sections: [{ children }],
	});

	const blob = await Packer.toBlob(document);
	triggerDownload(blob, "abtf-admin-report.docx");
}
